### ISSUE TITLE
Add wiki with supported languages

### ISSUE THREAD

**Issue by Juliusan** [atom-ide-community/atom-ide-languageclient#61]
Unsupported atom-languageclient package had a wiki with a nice [supported languages page](https://github.com/atom/atom-languageclient/wiki/List-of-Atom-packages-using-Atom-LanguageClient). However, it is not part of atom-ide-languageclient. In fact, you even link in a README.md to this non-existent wiki page (its on line 140 of commit 82f352a7a782362219b6a6b447ed03202d9ccf7d:
```
Our [full list of Atom IDE packages](https://github.com/atom-ide-community/atom-ide-languageclient/wiki/List-of-Atom-packages-using-Atom-LanguageClient) includes the community packages.
```
Could you please create at least this wiki page in this repository? I believe wiki of atom-languageclient may be cloned here: https://github.com/atom/atom-languageclient.wiki.git

By the way, I noticed it, because I've recently published [atom package](https://github.com/Juliusan/ide-erlang) to support [Erlang language](https://www.erlang.org/) IDE features. I would be grateful, if you add it to your the mentioned wiki page.

**Comment by UziTech** [comment]
I added the [wiki page](https://github.com/atom-ide-community/atom-ide-languageclient/wiki/List-of-Atom-packages-using-Atom-LanguageClient) and added erlang to the list of community packages.
